test yaml

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -92,7 +92,7 @@ jobs:
 
     - name: Remove existing .next folder on server
       run: |
-        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "source ~/.nvm/nvm.sh && nvm use v21.6.2 && pm2 del blog-next && rm -rf /root/projects/blog-next/.next"
+        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "source ~/.nvm/nvm.sh && nvm use v21.6.2 && pm2 id blog-next > /dev/null 2>&1 && pm2 del blog-next || echo 'blog-next process not found' && rm -rf /root/projects/blog-next/.next"
 
     - name: Transfer .next to Remote Server
       run: |
